### ISSUE TITLE
nodetool fails for me...

### ISSUE THREAD

**Issue by rthille** [tobert/cassandra-docker#12]
Environment: Ubuntu 14.04 VM (virtualbox) running on an Ubuntu 12.04 system (yeah, I need to upgrade...)

Cassandra itself comes up fine, and cqlsh works, but nodetool fails:
vagrant@vagrant-ubuntu-trusty-64:~/cassandra/tobert/cassandra-docker$ docker ps
CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS              PORTS                                                       NAMES
2a98b36187eb        tobert/cassandra:2.1.1   "/bin/cassandra-dock   9 seconds ago       Up 8 seconds        9042/tcp, 9160/tcp, 22/tcp, 61621/tcp, 7000/tcp, 7199/tcp   backstabbing_leakey   
2801b02c9b70        tobert/cassandra:2.1.1   "/bin/cassandra-dock   21 minutes ago      Up 21 minutes       9160/tcp, 22/tcp, 61621/tcp, 7000/tcp, 7199/tcp, 9042/tcp   elated_mayer    
      
vagrant@vagrant-ubuntu-trusty-64:~$ docker run -it --rm tobert/cassandra:2.1.1 nodetool 
Error: Could not find or load main class org.apache.cassandra.tools.NodeCmd

**Comment by rthille** [comment]
A couple more datapoints:
I can 'docker exec' the full path to nodetool and it works:
vagrant@vagrant-ubuntu-trusty-64:~$ docker exec -it 2801b02c9b70 /opt/apache-cassandra-2.1.1/bin/nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1  41.12 KB   256     100.0%            646ea139-fbac-48ba-90a9-9095d1728b1e  rack1

But without the path it fails:
vagrant@vagrant-ubuntu-trusty-64:~$ docker exec -it 2801b02c9b70 nodetool status
Error: Could not find or load main class org.apache.cassandra.tools.NodeCmd
vagrant@vagrant-ubuntu-trusty-64:~$

**Comment by Rickou412** [comment]
PR #3 on the road

**Comment by rthille** [comment]
Thanks a bunch @Rickou412 I've pulled it into my fork...

**Comment by tobert** [comment]
Oh, good catch. I'll merge this afternoon and publish updated images. Thanks!

**Comment by tobert** [comment]
OK, master is fixed and I've pushed 2.1.2 to Docker hub and tagged it latest.
