### ISSUE TITLE
"go build" builds "wrong" executable if you clone cassandra-docker into dir with different name...

### ISSUE THREAD

**Issue by rthille** [tobert/cassandra-docker#14]
I noticed when I cloned the repo that since I didn't use the default name of 'cassandra-docker' (I was evaluating a few different ones, so I renamed the checkout dir to something meaningful to me) that it "broke" things because the 'go build' built a different executable than the Dockerfile was expecting. Perhaps 'entrypoint.go' should be in a an appropriate 'cassandra-docker' subdirectory?

**Comment by rthille** [comment]
I'd PR a fix for this, but I'm not sure it's something you even want to address...

**Comment by tobert** [comment]
Hah! Yeah I suppose I ought to move it into a directory. I'll leave this open for now so I don't forget to do this. I'll probably also add a Makefile or build.sh so people don't need to mess with the go build.

**Comment by tobert** [comment]
Fixed by moving the code as discussed.
