### ISSUE TITLE
Port no. required for seeds?

### ISSUE THREAD

**Issue by tbsalling** [tobert/cassandra-docker#15]
I am trying to build a small cluster of Cassandra nodes running in Docker containers. I have two hosts each running two Docker containers. I need to pass the seeds around - but unless I used bridged networking in Docker - wouldn't I need to include port numbers for the list of seeds? I can't see any way this is possible.

Thanks,
/Thomas.

**Comment by tobert** [comment]
All of the ports have to be the same on all nodes for Cassandra. If you're running containers across multiple hosts, you will need to use --net=host to use the host networking to expose the ports directly, or use one of the fancy new SDN add-ons to Docker to provide a network where the ports can be matched and IPs can be guaranteed unique.

**Comment by tbsalling** [comment]
OK - thanks for the input!

I've just made the Docker containers connect to the physical LAN and use standard port no'.s based on the solution proposed in Lars Kellogg-Stedman's blog post ["Four ways to connect a docker container to a local network" - sect. "With Linux Bridge devices"](http://blog.oddbit.com/2014/08/11/four-ways-to-connect-a-docker/).
