### ISSUE TITLE
Add dc and rack flags

### ISSUE THREAD

**Issue by pofallon** [tobert/cassandra-docker#22]
It would be great to be able to pass in data center and/or rack flags and have those enable the GossipingPropertyFileSnitch and set the cassandra-rackdc.properties file accordingly.

**Comment by tobert** [comment]
Hmm. That will require a lot of flags. Can you mock up what the commands would look like to bring up a multi-dc cluster?

**Comment by pofallon** [comment]
Are you referring to the command line flags?  I was thinking `-name "My Cluster" -dc "DC1" -rack "RAC1"` etc.

These two flags, if present, would trigger two configuration file changes:  (1) the two values would be substituted into the "dc" and "rack" values of cassandra-rackdc.properties and (2) the "endpoint_snitch" property in cassandra.yaml would be set to "GossipingPropertyFileSnitch".

**Comment by pofallon** [comment]
This was closed by merging pull request #24 -- thanks for accepting the pull request!
