### ISSUE TITLE
Publish latest changes to Docker Hub?

### ISSUE THREAD

**Issue by pofallon** [tobert/cassandra-docker#27]
Is it possible to publish the latest changes to Docker Hub (specifically the merged `-dc` and `-rack` command line options)?  I want to point people directly at this docker repository but I need those command line options there first.

Thanks very much!

**Comment by tobert** [comment]
Oh, right! On it.

**Comment by pofallon** [comment]
Awesome, thank you!

**Comment by tobert** [comment]
Pushed. I didn't test it as much as usual, but your changes are in tobert/cassandra:2.1.4 which is also marked as latest.
