### ISSUE TITLE
Latest dockerhub image has issues

### ISSUE THREAD

**Issue by pofallon** [tobert/cassandra-docker#33]
If I launch a Cassandra node like this:
```
docker run --name n1 -d tobert/cassandra
```
and then try to run cqlsh, I get an error:
```
docker exec -it n1 cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```

However, this scenario works with the 2.1.4 tag.

**Comment by tobert** [comment]
Hmm. Yeah, JMX is probably binding to the container IP instead of localhost. I'll take a look.

**Comment by pofallon** [comment]
Thanks!  If you want to check in the changes to github, I'll try to help...

**Comment by tobert** [comment]
I pushed the latest code for Cassandra 2.1.7. The behavior around JMX port binding changed in 2.1.5 in upstream, but since this image doesn't use the stock shell scripts to start Cassandra, it should be using the original behavior. Testing now.

**Comment by tobert** [comment]
Oh, I see now. It's because Cassandra is binding to the host interface. Hmm.

**Comment by tobert** [comment]
Pushing the updated image to Docker hub now.

**Comment by pofallon** [comment]
Awesome!  Thanks so much -- I really appreciate it!
