### ISSUE TITLE
Wouldn't run on CoreOS without manually specifying memory

### ISSUE THREAD

**Issue by kristofferpeterhansel** [tobert/cassandra-docker#8]
So I am fairly new to Docker (and CoreOS - lots of things to play with). But I figured I'd give it a go with making a deployment of the solution we are currently developing. And since we are using Cassandra, this image seemed like a solid place to start.

But as one may guess from the subject, it wouldn't run. Looking a bit around for answers I discovered the answer in /srv/cassandra/log/console.log where this message kept appearing:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000731400000, 3293577216, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 3293577216 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
```

Adding a -m with sufficient memory (I started it out at 2g) fixed the issue for me. Not sure if it is CoreOS specific or what's going on. Couldn't see anything in your Dockerfile that should provoke issues like that anyway.

**Comment by tobert** [comment]
The new default as of 2f5cfb4a5e3cb4744b87ad9f022fd3e155ee4ef7 is 1GB heap with 256MB of new gen. Additionally, that commit adds the -heap and -new options which allow you to set your heap/new size at startup, which should cover your case.

See also: #18
